server:
  port: 8085
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启Feign对Sentinel的整合
hm:
  swagger:
    title: "交易服务接口文档"
    package: com.hmall.trade.controller
  db:
    database: hm-trade